### ISSUE TITLE
搞了个脚本，看看有没有帮助...

### ISSUE THREAD

**Issue by diredocks** [lbj96347/2020-virus-map#10]
写的很烂，业余的，轻喷。
https://github.com/Sudamid/wuhan-19nCov-news-reporter

**Comment by lbj96347** [comment]
@Sudamid 非常感谢！这个脚本对于我来说还是很有用的。今天我也在计划做相关的爬虫去爬取数据。其实最早启动项目的时候，我的期望是大家把最新看到的官方数据，用 pull request 的方式提上来。似乎大家都在忙着赶路。

**Comment by lbj96347** [comment]
@Sudamid 感谢你提供的帮助，我这边这两天也抓取了卫健委的网页，也尝试做了相关的解析。后来发现丁香园这边后来也把密度更新到城市了，并且也开始和「卫健委」的数据同步。

目前我会继续维护 https://github.com/lbj96347/2020-new-coronavirus-info-crawler 这个项目里面也有抓取丁香园数据的脚本，也有相关城市的经纬度信息。

 我也在思考，看下一步应该提供这样的数据可视化（比如交通信息），能够帮助到大家。
