### ISSUE TITLE
你还打算更新数据吗？

### ISSUE THREAD

**Issue by ferocknew** [lbj96347/2020-virus-map#12]

**Comment by lbj96347** [comment]
会更新数据的，昨天我也春运赶路。而且昨天一路上看到大家的评论，现在确实有点没有达到初衷「众人拾柴火焰高」。

我计划今天花时间去写爬虫了，已经有了相关的思路，爬虫完成后就会更新上来。:-)

**Comment by ferocknew** [comment]
辛苦，注意自身安全。我又一个QQ群，大家都很热心：735730057
提一些建议是否可行？

1. node 定时任务跑，服务器大家都有，可以协助，最后生成json（每5分钟）
2. 数据还是要有出处，避免不必要的麻烦，可以纠正，毕竟与跑批任务
3. 跑批生成数据根据城市获取经纬度
4. 爬虫结果自动生成json

以上欢迎到Q 群讨论

**Comment by lbj96347** [comment]
@ferocknew 是的，数据还是需要有出处的，为了避免大家猜疑，数据的源头还是得去政府，卫生委员会等官方机构的网站上面拿。

**Comment by ferocknew** [comment]
这也是为什么我积极参与这个项目，但是又希望和你沟通的原因：
我建议，并不只从这些渠道获取数据。
希望还包括

1. wiki 维基百科
2. BBC 新闻网、香港、台湾等媒体
3. 其他国家的官媒

**Comment by palorotolo** [comment]
好像意义不大，丁香医生的也差不多

**Comment by lbj96347** [comment]
@ferocknew 14 天过去了，我也做了相关的爬虫，持续地更新相关的数据。疫情已经复杂到超出所有人的想象。

@palorotolo 确实，如果单纯看数字的话，丁香医生已经满足了绝大部分人的需求。我这里原本想要输出的效果就是跟地理位置信息相结合，让大家避开这些疫情多发点。不过最近我有看到不少的小程序，或者是一些细化到小区的网站出来了，而且他们也更有相关的号召力，尤其是一些媒体。所以细化到地级市的地理位置信息已经没有太大的意义。

我觉得起码从启动这个项目的时候，能够吸引到不少人的注意，并且鼓励到大家在社区内贡献，并且生产出越来越多的点子帮助到大家隔离防控，帮助到有需要的人，尤其是湖北的朋友，已经非常足够了。

非常感谢二位提供的帮忙以及建议。
