### ISSUE TITLE
河南

### ISSUE THREAD

**Issue by 2218675712** [lbj96347/2020-virus-map#9]
河南郑州1例

**Comment by lbj96347** [comment]
@2218675712 不知道能否提供一下可靠的官方网站链接？感谢。

**Comment by 2218675712** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            
        
    
    
        
        

        
    

    在2020年1月21日 19:48，CashLee<notifications@github.com> 写道： 


@2218675712 不知道能否提供一下可靠的官方网站链接？感谢。

**Comment by 2218675712** [comment]
https://weibo.com/hnswsjsw?refer_flag=1005055014_&is_hot=1
这个是官方的微博

**Comment by lbj96347** [comment]
@2218675712 我已经找到了官方网站的链接。感谢提供：http://www.hnwsjsw.gov.cn/contents/177/47946.shtml
